openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-generic-domain
components:
  schemas:
    variables:
      type: object
      properties:
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          default: {}
          properties:
            domain_suffix:
              default: example.io
              description: |
                Specify the domain suffix for generating.
                The given domain suffix must be a valid domain name and has a Wildcard DNS record on your DNS resolver.
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        mode:
          title: Mode
          type: string
          description: |
            Specify the generation mode, select from contextual, random or timestamp.
          default: contextual
          enum:
          - contextual
          - random
          - timestamp
          x-walrus-ui:
            group: Basic
            order: 3
      x-walrus-ui:
        groupOrder:
        - Basic
        - Advanced
