openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-generic-domain
components:
  schemas:
    variables:
      required: []
      type: object
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.
          default: {}
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            hidden: true
            order: 1
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          default: {}
          properties:
            domain_suffix:
              description: |
                Specify the domain suffix for generating.
                The given domain suffix must be a valid domain name and has a Wildcard DNS record on your DNS resolver.
              default: "example.io"
              title: Domain Suffix
              type: string
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        mode:
          title: Mode
          type: string
          description: |
            Specify the generation mode, select from contextual, random or timestamp.
          default: contextual
          enum:
            - contextual
            - random
            - timestamp
          x-walrus-ui:
            group: Basic
            order: 3
      x-walrus-ui:
        groupOrder:
        - Basic
        - Advanced
